=== softtekAcademy/JavaCourse2016/JavaWeb-master/src/main/webapp/xml/XSD_Example.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://softtek.com/java/academy/web/XSDExample" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://softtek.com/java/academy/web/XSDExample">

    <element name="productList" type="tns:ProductListType"></element>

    <complexType name="ProductListType">
    	<sequence>
    		<element name="product" type="tns:ProductType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ProductType">
        <sequence>
            <element name="name" type="string"></element>
            <element name="price" type="double"></element>
            <element name="expiration" type="date"></element>
        </sequence>
        <attribute name="id" type="int"></attribute>
    </complexType>
</schema>

=== softtekAcademy/JavaCourse2016/JavaWeb-master/workspace/JavaWeb/src/main/webapp/xml/showXML-Expected.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<productList xmlns="http://softtek.com/java/academy/web/XSDExample" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:schemaLocation="http://softtek.com/java/academy/web/XSDExample XSD_Example.xsd ">
<!-- productList-->
    <product id="1">
        <name>Product 001</name>
        <price>14.90</price>
        <expiration>2016-02-01</expiration>
    </product>
    <product id="2">
        <name>Product 002</name>
        <price>85.00</price>
        <expiration>2016-02-01</expiration>
    </product>    
    <product id="3">
        <name>Product 003</name>
        <price>45.50</price>
        <expiration>2016-02-01</expiration>
    </product>
</productList>
